name: ENV_NAME
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py39h06a4308_0
  - comm=0.1.2=py39h06a4308_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - importlib-metadata=6.0.0=py39h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - ipykernel=6.19.2=py39hb070fc8_0
  - ipython=8.12.0=py39h06a4308_0
  - jedi=0.18.1=py39h06a4308_1
  - jupyter_client=8.1.0=py39h06a4308_0
  - jupyter_core=5.3.0=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py39h06a4308_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=23.0=py39h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.0.1=py39h06a4308_0
  - platformdirs=2.5.2=py39h06a4308_0
  - prompt-toolkit=3.0.36=py39h06a4308_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - python=3.9.16=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=23.2.0=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=66.0.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.2=py39h5eee18b_0
  - traitlets=5.7.1=py39h06a4308_0
  - typing_extensions=4.5.0=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - accelerate==0.18.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - async-timeout==4.0.2
    - attrs==23.1.0
    - banal==1.0.6
    - base58==2.1.1
    - blis==0.7.9
    - boto3==1.26.149
    - botocore==1.29.149
    - cached-path==1.1.6
    - cachetools==5.3.1
    - catalogue==2.0.8
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cmake==3.26.3
    - commonmark==0.9.1
    - cymem==2.0.7
    - datasets==2.12.0
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - en-core-web-sm==3.3.0
    - exceptiongroup==1.1.1
    - fairscale==0.4.6
    - filelock==3.7.1
    - frozenlist==1.3.3
    - fsspec==2023.4.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-api-core==2.11.0
    - google-auth==2.19.1
    - google-cloud-core==2.3.2
    - google-cloud-storage==2.9.0
    - google-crc32c==1.5.0
    - google-resumable-media==2.5.0
    - googleapis-common-protos==1.59.0
    - greenlet==2.0.2
    - h5py==3.8.0
    - huggingface-hub==0.15.1
    - idna==3.4
    - iniconfig==2.0.0
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - jsonnet==0.20.0
    - langcodes==3.3.0
    - lit==16.0.2
    - lmdb==1.4.1
    - mako==1.2.4
    - markupsafe==2.1.2
    - more-itertools==9.1.0
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.14
    - murmurhash==1.0.9
    - networkx==3.1
    - nltk==3.8.1
    - numpy==1.24.3
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - openai==0.27.4
    - pandas==2.0.0
    - pathtools==0.1.2
    - pathy==0.10.1
    - pillow==9.5.0
    - pluggy==1.0.0
    - preshed==3.0.8
    - promise==2.3
    - protobuf==3.20.3
    - pyarrow==12.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydantic==1.8.2
    - pyinflect==0.5.1
    - pytest==7.3.1
    - pytz==2023.3
    - pyyaml==6.0
    - regex==2023.3.23
    - requests==2.29.0
    - responses==0.18.0
    - rich==12.6.0
    - rsa==4.9
    - s3transfer==0.6.1
    - sacremoses==0.0.53
    - safetensors==0.3.1
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - sentencepiece==0.1.98
    - sentry-sdk==1.25.1
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - smart-open==6.3.0
    - smmap==5.0.0
    - spacy==3.3.3
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - sqlalchemy==1.4.48
    - srsly==2.4.6
    - sympy==1.11.1
    - tensorboardx==2.6
    - termcolor==1.1.0
    - thinc==8.0.17
    - threadpoolctl==3.1.0
    - tokenizers==0.13.3
    - tomli==2.0.1
    - torch==2.0.0
    - torchvision==0.13.1
    - tqdm==4.65.0
    - transformers==4.34.1
    - triton==2.0.0
    - typer==0.4.2
    - tzdata==2023.3
    - urllib3==1.26.15
    - wandb==0.12.21
    - wasabi==0.10.1
    - xxhash==3.2.0
    - yarl==1.9.1
prefix: /PATH_TO_YOUR_CONDA/miniconda3/envs/ENV_NAME
